---
booktitle: Proceedings of the Eighteenth International Conference on Artificial Intelligence
  and Statistics
volume: 38
year: '2015'
start: 2015-05-09
end: 2015-05-12
published: 2015-02-21
shortname: AISTATS
layout: proceedings
series: Proceedings of Machine Learning Research
issn: 1938-7228
id: AISTATS-2015
month: 0
cycles: false
editor:
- given: Guy
  family: Lebanon
- given: S. V. N.
  family: Vishwanathan
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Eighteenth International Conference on Artificial Intelligence and Statistics
    Held in San Diego, California, USA on 09-12 May 2015

  Published as Volume 38 by the Proceedings of Machine Learning Research on 21 February 2015.

  Volume Edited by:
    Guy Lebanon
    S. V. N. Vishwanathan

  Series Editors:
    Neil D. Lawrence
    Mark Reid
date_str: '09--12 May'
url: http://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v38"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
style: pmlr
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
permalink: "/:title.html"
ghub:
  edit: true
  repository: v38
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
    ris: true
  comments: false
email: ''
conference:
  name: Artificial Intelligence and Statistics
  url: http://www.aistats.org/aistats2015/
  location: San Diego, California, USA
  dates:
  - 2015-05-09
  - 2015-05-10
  - 2015-05-11
  - 2015-05-12
  number: 18
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/bibtex.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/bibtex.bib
